### ISSUE TITLE
[Artigo] Introdução

### ISSUE THREAD

**Issue by An-225** [pedrofgd/tcc-mack#57]
A introdução de conter 5 párágrafos com os seguintes conteúdos:

- [x] Ccontexto e motivação
      - Reforçar afirmações com artigos 
- [x] Problema
      - Detalhar o problema à se solucionado
- [x] Objetivo
      - Descrição curta da solução que foi desenvolvida
- [x] Explicação do objetivo
      - Escrever elementos da solução desenvolvida
- [x] Próximas seções
      - Listar próximas seções do tcc

**Comment by pedrofgd** [comment]
Versão final 1 para revisão entregue! As eventuais correções e melhorias poderão ficar em outras issues
