### ISSUE TITLE
[Artigo] Referencial Teórico

### ISSUE THREAD

**Issue by An-225** [pedrofgd/tcc-mack#58]
Esta seção do artigo deve conter todo o referencial teórico utilizado para o desenvolvimento da solução,
Podemos reutilizar boa parte do TCC I.
Obs.: Deve ter de 4-6 páginas

**Comment by pedrofgd** [comment]
Versão final 1 para revisão entrega! As eventuais correções e melhorias poderão ficar em outras issues
