### ISSUE TITLE
[Artigo] Método de pesquisa

### ISSUE THREAD

**Issue by An-225** [pedrofgd/tcc-mack#59]
Apresentar o método de design science do Wieringa.
Temos isso escrito no TCC I, acho necessário somente revisar se está tudo certo.
Obs.: Professora pediu 2 páginas, vamos ter que enrolar um pouco....

**Comment by pedrofgd** [comment]
@An-225 ela pediu 2 páginas, mas deixamos uma só...
Vamos ver no que vai dar

**Comment by pedrofgd** [comment]
Fechado essa pois o artigo já foi enviado para revisão e vamos tratar as melhorias em #85
